---
- name: Configuración general de las máquinas
  hosts: all
  remote_user: adminUsername
  become: true
  tasks:
    - name: Actualizamos la máquina
      command: dnf update -y

    - name: Tareas previas a la configuración
      shell: |
        timedatectl set-timezone Europe/Madrid 
        dnf install chrony -y
        systemctl enable chronyd
        systemctl start chronyd
        systemctl enable firewalld
        systemctl start firewalld
        timedatectl set-ntp true
        sed -i s/=enforcing/=disabled/g /etc/selinux/config

    - name: Iniciar servicios chronyd y firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - chronyd
        - firewalld

    - name: Instalar nfs-utils nfs4-acl-tools y wget
      dnf:
        name:
          - nfs-utils
          - nfs4-acl-tools
          - wget
        state: latest
  
    #Configuración de servicio NFS
    - name: Subiendo /etc/hosts con nombres de hosts
      copy:
        src: /home/domingo/hosts
        dest: /etc/hosts2
        owner: adminUsername
        group: adminUsername
        mode: 0644

    - name: Añadiendo a /etc/hosts
      command: bash -c 'cat /etc/hosts2 >> /etc/hosts'

- name: Configuración NFS
  hosts: master
  remote_user: adminUsername
  become: true
  tasks:
    #Encendido de servicio NFS
    - name: Instalar nfs-utils y net-tools
      dnf:
        name:
          - nfs-utils
          - net-tools
        state: latest

    - name: Arrancamos el servicio de NFS
      systemd:
        name: nfs-server
        state: started
        enabled: yes

    #Configuración de servicio NFS
    - name: Subiendo /etc/exports
      copy:
        src: /home/domingo/exports
        dest: /etc/exports 
        owner: adminUsername
        group: adminUsername
        mode: 0644

    - name: Aplicamos la configuración de NFS
      shell: |
        exportfs -r
        exportfs -s

    #Configuración de firewall
    - name: Apertura de puertos en el firewall
      shell: |
        firewall-cmd --permanent --add-service=nfs
        firewall-cmd --permanent --add-service=rpc-bind
        firewall-cmd --permanent --add-service=mountd
        firewall-cmd --reload