---
- name: Configuración general de las máquinas
  hosts: all
  remote_user: adminUsername
  become: true
  tasks:
    - name: Actualizamos la máquina
      command: dnf update -y

    - name: Tareas previas a la configuración
      shell: |
        timedatectl set-timezone Europe/Madrid 
        dnf install chrony -y
        systemctl enable chronyd
        systemctl start chronyd
        timedatectl set-ntp true
        sed -i s/=enforcing/=disabled/g /etc/selinux/config

    - name: Instalar nfs-utils nfs4-acl-tools y wget
      dnf:
        name:
          - nfs-utils
          - nfs4-acl-tools
          - wget
        state: latest
  
    #Configuración de servicio NFS
    - name: Subiendo /etc/hosts con nombres de hosts
      copy:
        src: /home/domingo/hosts
        dest: /etc/hosts2
        owner: adminUsername
        group: adminUsername
        mode: 0644

    - name: Añadiendo a /etc/hosts
      command: bash -c 'cat /etc/hosts2 >> /etc/hosts'

- name: Configuración NFS
  hosts: nfs
  remote_user: adminUsername
  become: true
  tasks:
    - name: Mostrar listado de Discos
      command: lsblk
      register: disklist

    - debug: msg="{{ disklist.stdout }}"

    #Creación de Volume Group sobre disco montado
    - name: Creación de Volume Group para NFS
      shell: |
        pvcreate /dev/sdc
        vgcreate data_vg /dev/sdc

    - name: Mostrar listado de Volume Groups
      command: vgdisplay data_vg
      register: vg

    - debug: msg="{{ vg.stdout }}"

    #Creación de Logical Volume sobre disco montado
    - name: Creación de Logical Volume para NFS
      command: lvcreate -l+2559 -n nfs_lv /dev/data_vg

    - name: Mostrar listado de Logical Volumes
      command: lvs
      register: lv

    - debug: msg="{{ lv.stdout }}"

    #Creación de filesystem tipo XFS
    - name: Creación de filesystem de tipo XFS
      shell: |
        mkfs.xfs /dev/data_vg/nfs_lv
        mkdir /srv/nfs
        echo "/dev/data_vg/nfs_lv        /srv/nfs                xfs     defaults        0 0" >> /etc/fstab
        mount -a

    - name: Mostrar discos montados
      command: df -hP
      register: df

    - debug: msg="{{ df.stdout }}"

    #Encendido de servicio NFS
    - name: Instalar nfs-utils y net-tools
      dnf:
        name:
          - nfs-utils
          - net-tools
        state: latest

    - name: Arrancamos el servicio de NFS
      shell: |
        systemctl enable nfs-server
        systemctl start nfs-server

    #Configuración de servicio NFS
    - name: Subiendo /etc/exports
      copy:
        src: /home/domingo/exports
        dest: /etc/exports 
        owner: adminUsername
        group: adminUsername
        mode: 0644

    - name: Aplicamos la configuración de NFS
      shell: |
        exportfs -r
        exportfs -s

    #Configuración de firewall
    - name: Apertura de puertos en el firewall
      shell: |
        firewall-cmd --permanent --add-service=nfs
        firewall-cmd --permanent --add-service=rpc-bind
        firewall-cmd --permanent --add-service=mountd
        firewall-cmd --reload